"""create prompts table

Revision ID: 0d3fcdc33602
Revises: a1b2c3d4e5f6
Create Date: 2026-01-02 12:05:36.240698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d3fcdc33602'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Prompt identifier, unique per user (e.g., 'code-review')"),
    sa.Column('title', sa.String(length=500), nullable=True, comment="Optional display title (e.g., 'Code Review Assistant')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description'),
    sa.Column('content', sa.Text(), nullable=True, comment='Jinja2 template content'),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Prompt arguments: [{name: str, description: str?, required: bool?}]'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_prompts_user_name')
    )
    op.create_index(op.f('ix_prompts_updated_at'), 'prompts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_prompts_user_id'), 'prompts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_user_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_updated_at'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
