"""add changed_fields to content_history

Revision ID: 1b278625065d
Revises: 261e9a509112
Create Date: 2026-02-13 20:30:11.153762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b278625065d'
down_revision: Union[str, Sequence[str], None] = '261e9a509112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_history', sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_history', 'changed_fields')
    # ### end Alembic commands ###
