"""drop redundant user_id index on content_relationships

Revision ID: 261e9a509112
Revises: 400ac01d8c8d
Create Date: 2026-02-13 12:39:23.729343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261e9a509112'
down_revision: Union[str, Sequence[str], None] = '400ac01d8c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_relationships_user_id'), table_name='content_relationships')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_content_relationships_user_id'), 'content_relationships', ['user_id'], unique=False)
    # ### end Alembic commands ###
