"""add content_relationships table

Revision ID: 400ac01d8c8d
Revises: 7b2e0552ad5f
Create Date: 2026-02-11 10:16:03.473348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '400ac01d8c8d'
down_revision: Union[str, Sequence[str], None] = '7b2e0552ad5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_relationships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.CheckConstraint("relationship_type IN ('related')", name='ck_relationship_type'),
    sa.CheckConstraint("source_type IN ('bookmark', 'note', 'prompt')", name='ck_source_type'),
    sa.CheckConstraint("target_type IN ('bookmark', 'note', 'prompt')", name='ck_target_type'),
    sa.CheckConstraint('NOT (source_type = target_type AND source_id = target_id)', name='ck_no_self_reference'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_type', 'source_id', 'target_type', 'target_id', 'relationship_type', name='uq_content_relationship')
    )
    op.create_index('ix_content_rel_source', 'content_relationships', ['user_id', 'source_type', 'source_id'], unique=False)
    op.create_index('ix_content_rel_target', 'content_relationships', ['user_id', 'target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_content_relationships_updated_at'), 'content_relationships', ['updated_at'], unique=False)
    op.create_index(op.f('ix_content_relationships_user_id'), 'content_relationships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_relationships_user_id'), table_name='content_relationships')
    op.drop_index(op.f('ix_content_relationships_updated_at'), table_name='content_relationships')
    op.drop_index('ix_content_rel_target', table_name='content_relationships')
    op.drop_index('ix_content_rel_source', table_name='content_relationships')
    op.drop_table('content_relationships')
    # ### end Alembic commands ###
