"""add content_chunks and content_embedding_state tables

Revision ID: 577108e3d7b9
Revises: 37924b35a9a8
Create Date: 2026-04-08 21:13:57.147303

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy.vector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577108e3d7b9'
down_revision: Union[str, Sequence[str], None] = '37924b35a9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    op.create_table('content_chunks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_type', sa.String(length=20), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('chunk_hash', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'chunk_type', 'chunk_index', name='uq_content_chunks_entity_chunk')
    )
    op.create_index('ix_content_chunks_entity', 'content_chunks', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_content_chunks_user_id', 'content_chunks', ['user_id'], unique=False)
    op.execute(
        "CREATE INDEX ix_content_chunks_embedding ON content_chunks "
        "USING hnsw (embedding vector_cosine_ops);"
    )
    op.create_table('content_embedding_state',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('metadata_hash', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("status IN ('embedded', 'failed')", name='ck_content_embedding_state_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_content_embedding_state_entity')
    )
    op.create_index('ix_content_embedding_state_status', 'content_embedding_state', ['status'], unique=False)
    op.create_index('ix_content_embedding_state_user_id', 'content_embedding_state', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_content_embedding_state_user_id', table_name='content_embedding_state')
    op.drop_index('ix_content_embedding_state_status', table_name='content_embedding_state')
    op.drop_table('content_embedding_state')
    op.drop_index('ix_content_chunks_embedding', table_name='content_chunks')
    op.drop_index('ix_content_chunks_user_id', table_name='content_chunks')
    op.drop_index('ix_content_chunks_entity', table_name='content_chunks')
    op.drop_table('content_chunks')
    # Intentionally not dropping the vector extension — it may be used by other
    # objects, and DROP EXTENSION vector CASCADE would destroy them.
    # ### end Alembic commands ###
