"""add public sharing fields to content models

Revision ID: 5fd6c03a4e43
Revises: 38f5a24e651f
Create Date: 2026-06-18 15:49:43.906398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fd6c03a4e43'
down_revision: Union[str, Sequence[str], None] = '38f5a24e651f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('bookmarks', sa.Column('public_token', sa.String(length=64), nullable=True))
    op.create_index('uq_bookmark_public_token', 'bookmarks', ['public_token'], unique=True, postgresql_where=sa.text('public_token IS NOT NULL'))
    op.add_column('notes', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('notes', sa.Column('public_token', sa.String(length=64), nullable=True))
    op.create_index('uq_note_public_token', 'notes', ['public_token'], unique=True, postgresql_where=sa.text('public_token IS NOT NULL'))
    op.add_column('prompts', sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('prompts', sa.Column('public_token', sa.String(length=64), nullable=True))
    op.create_index('uq_prompt_public_token', 'prompts', ['public_token'], unique=True, postgresql_where=sa.text('public_token IS NOT NULL'))
    # CheckConstraints are not detected by autogenerate; added manually to match
    # the model __table_args__. A published item must always have a share token.
    op.create_check_constraint('ck_bookmark_public_requires_token', 'bookmarks', 'NOT is_public OR public_token IS NOT NULL')
    op.create_check_constraint('ck_note_public_requires_token', 'notes', 'NOT is_public OR public_token IS NOT NULL')
    op.create_check_constraint('ck_prompt_public_requires_token', 'prompts', 'NOT is_public OR public_token IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_prompt_public_requires_token', 'prompts', type_='check')
    op.drop_constraint('ck_note_public_requires_token', 'notes', type_='check')
    op.drop_constraint('ck_bookmark_public_requires_token', 'bookmarks', type_='check')
    op.drop_index('uq_prompt_public_token', table_name='prompts', postgresql_where=sa.text('public_token IS NOT NULL'))
    op.drop_column('prompts', 'public_token')
    op.drop_column('prompts', 'is_public')
    op.drop_index('uq_note_public_token', table_name='notes', postgresql_where=sa.text('public_token IS NOT NULL'))
    op.drop_column('notes', 'public_token')
    op.drop_column('notes', 'is_public')
    op.drop_index('uq_bookmark_public_token', table_name='bookmarks', postgresql_where=sa.text('public_token IS NOT NULL'))
    op.drop_column('bookmarks', 'public_token')
    op.drop_column('bookmarks', 'is_public')
    # ### end Alembic commands ###
