"""add deleted_identities tombstone table

Revision ID: 64e3641d3441
Revises: 0b5c5e3e2ff4
Create Date: 2026-07-13 13:54:45.611545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e3641d3441'
down_revision: Union[str, Sequence[str], None] = '0b5c5e3e2ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The autogenerated search_vector GIN index drops were spurious (those
    # indexes come from a raw-SQL/trigger migration and aren't visible to
    # Alembic metadata) and were removed, per the precedent in 77ccf8214c82.
    op.create_table('deleted_identities',
    sa.Column('auth0_id', sa.String(length=255), nullable=True, comment="Auth0 'sub' of the deleted user - blocks the Auth0/iOS JIT path"),
    sa.Column('external_auth_id', sa.String(length=255), nullable=True, comment="Clerk user ID ('sub') of the deleted user - blocks the Clerk JIT path"),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.CheckConstraint('(auth0_id IS NOT NULL) OR (external_auth_id IS NOT NULL)', name='ck_deleted_identity_has_identity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_identities_auth0_id'), 'deleted_identities', ['auth0_id'], unique=True)
    op.create_index(op.f('ix_deleted_identities_external_auth_id'), 'deleted_identities', ['external_auth_id'], unique=True)
    op.create_index(op.f('ix_deleted_identities_updated_at'), 'deleted_identities', ['updated_at'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_deleted_identities_updated_at'), table_name='deleted_identities')
    op.drop_index(op.f('ix_deleted_identities_external_auth_id'), table_name='deleted_identities')
    op.drop_index(op.f('ix_deleted_identities_auth0_id'), table_name='deleted_identities')
    op.drop_table('deleted_identities')
