"""add tier column to users

Revision ID: 6db191fb52c6
Revises: 0b7c0827313e
Create Date: 2026-02-01 15:03:16.055210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6db191fb52c6'
down_revision: Union[str, Sequence[str], None] = '0b7c0827313e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_filters', 'content_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Content types this filter applies to: bookmark, note, prompt',
               existing_comment='Content types this list applies to: bookmark, note, todo',
               existing_nullable=False,
               existing_server_default=sa.text('\'["bookmark"]\'::jsonb'))
    op.add_column('users', sa.Column('tier', sa.String(length=50), server_default='free', nullable=False, comment="User subscription tier (e.g., 'free', 'pro')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tier')
    op.alter_column('content_filters', 'content_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Content types this list applies to: bookmark, note, todo',
               existing_comment='Content types this filter applies to: bookmark, note, prompt',
               existing_nullable=False,
               existing_server_default=sa.text('\'["bookmark"]\'::jsonb'))
    # ### end Alembic commands ###
