"""add shared_at to content models

Revision ID: 77ccf8214c82
Revises: 5fd6c03a4e43
Create Date: 2026-06-21 09:49:56.222797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ccf8214c82'
down_revision: Union[str, Sequence[str], None] = '5fd6c03a4e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the nullable shared_at column to each content table. The autogenerated
    # search_vector GIN index drops are spurious — those indexes are created by a
    # raw-SQL/trigger migration and aren't visible to Alembic metadata, so they
    # must not be touched here.
    #
    # No backfill: the app guarantees the invariant "is_public ⟹ shared_at set"
    # at the only write path (BaseEntityService.set_share_state stamps shared_at
    # on every publish). The whole sharing feature ships in one migration batch
    # with this column, so no pre-existing is_public=true row can exist for a
    # backfill to touch. If a future non-set_share_state writer ever sets
    # is_public, fix it there (or add a DB constraint) rather than here.
    op.add_column('bookmarks', sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notes', sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('prompts', sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('prompts', 'shared_at')
    op.drop_column('notes', 'shared_at')
    op.drop_column('bookmarks', 'shared_at')
