"""add prompts table and prompt_tags

Revision ID: 8778dc234eac
Revises: a1b2c3d4e5f6
Create Date: 2026-01-03 13:06:57.027956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8778dc234eac'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_archived_at'), 'prompts', ['archived_at'], unique=False)
    op.create_index(op.f('ix_prompts_deleted_at'), 'prompts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_prompts_last_used_at'), 'prompts', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_prompts_updated_at'), 'prompts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_prompts_user_id'), 'prompts', ['user_id'], unique=False)
    # Partial unique index: name must be unique per user for active (non-deleted) prompts
    op.create_index(
        'uq_prompt_user_name_active',
        'prompts',
        ['user_id', 'name'],
        unique=True,
        postgresql_where=sa.text('deleted_at IS NULL'),
    )
    op.create_table('prompt_tags',
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prompt_id', 'tag_id')
    )
    op.create_index('ix_prompt_tags_tag_id', 'prompt_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prompt_tags_tag_id', table_name='prompt_tags')
    op.drop_table('prompt_tags')
    op.drop_index('uq_prompt_user_name_active', table_name='prompts')
    op.drop_index(op.f('ix_prompts_user_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_updated_at'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_last_used_at'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_deleted_at'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_archived_at'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
