"""add content_history table and drop note_versions

Revision ID: a6bf6790021d
Revises: 6db191fb52c6
Create Date: 2026-02-04 20:10:33.140014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6bf6790021d'
down_revision: Union[str, Sequence[str], None] = '6db191fb52c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('diff_type', sa.String(length=20), nullable=False),
    sa.Column('content_snapshot', sa.Text(), nullable=True),
    sa.Column('content_diff', sa.Text(), nullable=True),
    sa.Column('metadata_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('auth_type', sa.String(length=10), nullable=False),
    sa.Column('token_prefix', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', 'version', name='uq_content_history_version')
    )
    op.create_index('ix_content_history_created', 'content_history', ['created_at'], unique=False)
    op.create_index('ix_content_history_snapshots', 'content_history', ['user_id', 'entity_type', 'entity_id', 'version'], unique=False, postgresql_where=sa.text("diff_type = 'snapshot'"))
    op.create_index('ix_content_history_user_created', 'content_history', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_content_history_user_entity', 'content_history', ['user_id', 'entity_type', 'entity_id', 'version'], unique=False)
    op.drop_index(op.f('ix_note_versions_note_id_version'), table_name='note_versions')
    op.drop_table('note_versions')
    op.drop_column('notes', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False, server_default=sa.text('1')))
    op.create_table('note_versions',
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment="'snapshot' for full content, 'diff' for diff-match-patch delta"),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='Full content if snapshot, diff if diff type'),
    sa.Column('saved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('note_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('note_versions_note_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('note_versions_pkey'))
    )
    op.create_index(op.f('ix_note_versions_note_id_version'), 'note_versions', ['note_id', 'version'], unique=False)
    op.drop_index('ix_content_history_user_entity', table_name='content_history')
    op.drop_index('ix_content_history_user_created', table_name='content_history')
    op.drop_index('ix_content_history_snapshots', table_name='content_history', postgresql_where=sa.text("diff_type = 'snapshot'"))
    op.drop_index('ix_content_history_created', table_name='content_history')
    op.drop_table('content_history')
    # ### end Alembic commands ###
