"""fix note_versions note_id nullable

The UUID7 migration (9e7d4c4a8c2a) accidentally left note_versions.note_id
as nullable after the column swap. The model expects NOT NULL.

Revision ID: cc7d7d58ce2e
Revises: 452f28fc1e2a
Create Date: 2026-01-07 10:21:51.609505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc7d7d58ce2e'
down_revision: Union[str, Sequence[str], None] = '452f28fc1e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('note_versions', 'note_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_consents', 'user_id',
               existing_type=sa.UUID(),
               comment='Foreign key to users table - one consent record per user',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_consents', 'user_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Foreign key to users table - one consent record per user',
               existing_nullable=False)
    op.alter_column('note_versions', 'note_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
