"""Add notes and note_versions tables with note_tags junction

Revision ID: e1954a7343da
Revises: a78e8972446e
Create Date: 2025-12-26 14:25:35.491132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1954a7343da'
down_revision: Union[str, Sequence[str], None] = 'a78e8972446e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_deleted_at'), 'notes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_notes_last_used_at'), 'notes', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('note_tags',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'tag_id')
    )
    op.create_index('ix_note_tags_tag_id', 'note_tags', ['tag_id'], unique=False)
    op.create_table('note_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('version_type', sa.String(length=20), nullable=False, comment="'snapshot' for full content, 'diff' for diff-match-patch delta"),
    sa.Column('content', sa.Text(), nullable=False, comment='Full content if snapshot, diff if diff type'),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Composite index for the primary query pattern:
    # SELECT * FROM note_versions WHERE note_id = ? ORDER BY version
    op.create_index('ix_note_versions_note_id_version', 'note_versions', ['note_id', 'version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_note_versions_note_id_version', table_name='note_versions')
    op.drop_table('note_versions')
    op.drop_index('ix_note_tags_tag_id', table_name='note_tags')
    op.drop_table('note_tags')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_last_used_at'), table_name='notes')
    op.drop_index(op.f('ix_notes_deleted_at'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
