name: extension-tests

on:
  push:
    branches: ["main", "staging"]
    paths:
      - 'chrome-extension/**'
      - '.github/workflows/extension-tests.yaml'
  pull_request:
    branches: ["main", "staging"]
    paths:
      - 'chrome-extension/**'
      - '.github/workflows/extension-tests.yaml'
  workflow_dispatch:

jobs:
  extension:
    name: Extension Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'chrome-extension/.nvmrc'
          cache: 'npm'
          cache-dependency-path: chrome-extension/package-lock.json
      - run: make extension-install
      - run: make extension-tests
